trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S terraform Azure!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'Azure subscription 1(4b3ef37a-20b7-462e-bd13-14839c122b92)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccountrobles'
    backendAzureRmContainerName: 'storageaccountcontainer'
    backendAzureRmKey: 'kubernates-dev.tfstate'

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-resource-manager-service-connection'
    secureVarsFile: '$(publickey.secureFile)'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret)'

    



