trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo AWS IAAC, example!
  displayName: 'Run a one-line script'

## init terraform backend
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state-in28minutes-br'
    backendAWSKey: 'kubernetes-dev.tfstate'
## terraform apply
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-for-terraform'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-for-terraform'
